version: "3.8"
services:
  printer:
    container_name: printer
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./printer_storage/.moonraker_database:/home/printer/.moonraker_database:delegated
      - ./printer_storage/gcode_files:/home/printer/gcode_files:delegated
      - ./printer_storage/klipper_config:/home/printer/klipper_config:delegated
      - ./printer_storage/klipper_logs:/home/printer/klipper_logs:delegated
    ports:
      - "7125:7125"
      - "8110:8080"
    networks:
      - dev_net
networks:
  dev_net:
    driver: bridge
